version: "3"
services:
    rockylinux:
        container_name: test1
        build: ./rocky/
        ports:
            - "1222:222"
    centos:
        container_name: test2
        build: ./centos/
        ports:
            - "2222:222"
    ubuntu:
        container_name: test3
        build: ./ubuntu/
        ports:
            - "3222:222"
    ansible:
        container_name: ansible
        build: ./ansible/
